# Generated by Django 5.2.17 on 2026-09-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private_cofinanced', 'Private cofinanced'), ('private_selffinanced', 'Private self-financed')], max_length=32)),
                ('website', models.URLField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('needs_review', 'Needs review')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'universities',
                'ordering': ['name'],
            },
        ),
    ]
