# Generated by Django 5.2.17 on 2026-09-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='jobs_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
