# Generated by Django 5.2.17 on 2026-09-25 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0001_initial'),
        ('universities', '0003_set_espe_jobs_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('module_path', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('timeout', models.PositiveIntegerField(default=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='idle', max_length=20)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectors', to='universities.university')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
