# Generated by Django 5.2.17 on 2026-09-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0003_seed_espe_collector'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('acquired_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
