# Generated by Django 5.2.17 on 2026-09-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0004_schedulerlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='date_selector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collector',
            name='description_selector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collector',
            name='link_selector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collector',
            name='list_selector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collector',
            name='title_selector',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
