# Generated by Django 5.2.17 on 2026-09-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0005_collector_date_selector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='exclude_patterns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='include_patterns',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='allowed_extensions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='blocked_extensions',
            field=models.TextField(blank=True),
        ),
    ]
