# Generated by Django 5.2.17 on 2026-09-25 23:57

import django.db.models.deletion
from django.db import migrations, models


def create_collector_templates(apps, schema_editor):
    CollectorTemplate = apps.get_model('collectors', 'CollectorTemplate')
    CollectorTemplate.objects.get_or_create(
        name='Article cards',
        defaults={
            'description': 'Common semantic HTML job cards using article elements.',
            'list_selector': 'article.job-card',
            'title_selector': '.title',
            'link_selector': 'a.details',
            'date_selector': '.date',
            'description_selector': '.summary',
        },
    )


def remove_collector_templates(apps, schema_editor):
    CollectorTemplate = apps.get_model('collectors', 'CollectorTemplate')
    CollectorTemplate.objects.filter(name='Article cards').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0006_collector_exclude_patterns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('list_selector', models.CharField(max_length=255)),
                ('title_selector', models.CharField(max_length=255)),
                ('link_selector', models.CharField(max_length=255)),
                ('date_selector', models.CharField(blank=True, max_length=255)),
                ('description_selector', models.CharField(blank=True, max_length=255)),
                ('include_patterns', models.TextField(blank=True)),
                ('exclude_patterns', models.TextField(blank=True)),
                ('allowed_extensions', models.TextField(blank=True)),
                ('blocked_extensions', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='collector',
            name='health_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('empty', 'No jobs found'), ('error', 'Error')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='collector',
            name='last_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='last_job_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collector',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectors', to='collectors.collectortemplate'),
        ),
        migrations.RunPython(create_collector_templates, remove_collector_templates),
    ]
