# Generated by Django 5.2.17 on 2026-09-26 00:05

from django.db import migrations, models


def increase_default_timeouts(apps, schema_editor):
    Collector = apps.get_model('collectors', 'Collector')
    Collector.objects.filter(timeout=20).update(timeout=30)


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0007_collectortemplate_collector_health_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorexecution',
            name='error_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='collector',
            name='timeout',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.RunPython(increase_default_timeouts, migrations.RunPython.noop),
    ]
