# Generated by Django 5.2.17 on 2026-09-26 00:20

from django.db import migrations, models


GENERIC_COLLECTOR = 'collectors.generic_html.GenericHTMLCollector'


SOURCES = {
    'usfq': {
        'university': 'Universidad San Francisco de Quito',
        'url': 'https://www.usfq.edu.ec/es/trabaja-con-nosotros/vacantes-abiertas',
        'template': 'USFQ vacancy cards',
        'selectors': {
            'list_selector': "//div[contains(concat(' ', normalize-space(@class), ' '), ' modal ')][.//h5[contains(@class, 'modal-title')]]",
            'title_selector': '.modal-title',
            'link_selector': './@id',
            'date_selector': ".//p[strong[contains(normalize-space(.), 'Publicado')]]",
            'deadline_selector': ".//p[strong[contains(normalize-space(.), 'Aplicaciones hasta')]]",
            'description_selector': '.modal-body',
            'exclude_patterns': 'finalizado\ncerrada\narchivo\nhist[oó]ric',
        },
    },
    'puce': {
        'university': 'Pontificia Universidad Catolica del Ecuador',
        'url': 'https://cisealpuce.edu.ec/nosotros/trabajo.html',
        'template': 'PUCE CISeAL vacancies',
        'selectors': {
            'list_selector': "//div[@itemprop='articleBody']//a[contains(translate(@href, 'PDF', 'pdf'), '.pdf')]",
            'title_selector': './self::*',
            'link_selector': './@href',
            'description_selector': './parent::*',
            'exclude_patterns': 'cerrad[ao]\nfinalizad[ao]\nexpirad[ao]\narchivo\nhist[oó]ric',
        },
    },
    'espol': {
        'university': 'Escuela Superior Politecnica del Litoral',
        'url': 'https://www.espol.edu.ec/es/concurso-meritos-2026',
        'template': 'ESPOL academic contest table',
        'selectors': {
            'list_selector': "//table[contains(@class, 'tabla_datos')]/tbody/tr[not(td[9]//a)]",
            'title_selector': 'td:nth-child(3)',
            'link_selector': 'td:nth-child(6) a',
            'description_selector': 'td:nth-child(4)',
            'include_patterns': 'profesor',
            'exclude_patterns': 'acta de resultados\nresultados finales\nfinalizad[ao]\ncerrad[ao]',
        },
    },
    'epn': {
        'university': 'Escuela Politecnica Nacional',
        'url': 'https://www.epn.edu.ec/?s=OFERTA+LABORAL',
        'template': 'EPN recent vacancy search',
        'selectors': {
            'list_selector': "//div[contains(@class, 'edubin-post-one-single-grid')][.//img[contains(@src, '/2026/09/')]]",
            'title_selector': '.course__title-link',
            'link_selector': '.course__title-link',
            'description_selector': '.card-bottom',
            'include_patterns': 'oferta laboral',
            'exclude_patterns': 'jardinero\nservidor p[uú]blico 6\nfinalizad[ao]\ncerrad[ao]',
        },
    },
    'utpl': {
        'university': 'Universidad Tecnica Particular de Loja',
        'url': 'https://utpl.hiringroom.com/jobs',
        'template': 'HiringRoom vacancy cards',
        'selectors': {
            'list_selector': '.vacancyDataContainer > a',
            'title_selector': '.name__vacancy',
            'link_selector': './@href',
            'date_selector': '.vacancy-time',
            'description_selector': '.card-text',
            'include_patterns': 'vacante\nconvocatoria\ndocente\nprofesor\ninvestigador\npasant[ií]a',
            'exclude_patterns': 'cerrad[ao]\nfinalizad[ao]\nexpirad[ao]\narchivo\nhist[oó]ric',
        },
    },
}


def configure_first_universities(apps, schema_editor):
    Collector = apps.get_model('collectors', 'Collector')
    CollectorTemplate = apps.get_model('collectors', 'CollectorTemplate')
    University = apps.get_model('universities', 'University')
    for priority, (name, source) in enumerate(SOURCES.items(), start=11):
        university = University.objects.filter(name=source['university']).first()
        if university is None:
            continue
        university.jobs_url = source['url']
        university.save(update_fields=['jobs_url', 'updated_at'])
        template, _ = CollectorTemplate.objects.update_or_create(
            name=source['template'],
            defaults={
                'description': f"VS012 selectors for {source['university']}.",
                **source['selectors'],
            },
        )
        Collector.objects.update_or_create(
            name=name,
            defaults={
                'university': university,
                'template': template,
                'module_path': GENERIC_COLLECTOR,
                'enabled': True,
                'priority': priority * 10,
                'timeout': 30,
                'max_age_days': 30,
                'status': 'idle',
            },
        )


def remove_first_universities(apps, schema_editor):
    Collector = apps.get_model('collectors', 'Collector')
    CollectorTemplate = apps.get_model('collectors', 'CollectorTemplate')
    University = apps.get_model('universities', 'University')
    Collector.objects.filter(name__in=SOURCES).delete()
    CollectorTemplate.objects.filter(
        name__in=[source['template'] for source in SOURCES.values()]
    ).delete()
    University.objects.filter(
        name__in=[source['university'] for source in SOURCES.values()]
    ).update(jobs_url='')


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0008_collectorexecution_error_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='deadline_selector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collector',
            name='max_age_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectortemplate',
            name='deadline_selector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(configure_first_universities, remove_first_universities),
    ]
