# Generated by Django 5.2.17 on 2026-09-26 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_job_contract_type_job_keywords_job_language_and_more'),
        ('profiles', '0003_jobmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SAVED', 'Saved'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='SAVED', max_length=20)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('interview_at', models.DateTimeField(blank=True, null=True)),
                ('offer_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('researcher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.researcherprofile')),
            ],
            options={
                'ordering': ['-saved_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('researcher_profile', 'job'), name='unique_researcher_job_application')],
            },
        ),
    ]
