# Generated by Django 5.2.17 on 2026-09-25 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0003_set_espe_jobs_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=80)),
                ('external_id', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('closed', 'Closed')], default='new', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(blank=True, max_length=120)),
                ('discipline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='universities.university')),
            ],
            options={
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_job_source_external_id')],
            },
        ),
    ]
