# Generated by Django 5.2.17 on 2026-09-26 13:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0003_set_espe_jobs_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('weight', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearcherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('highest_degree', models.CharField(blank=True, max_length=120)),
                ('current_position', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('preferred_employment_types', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('minimum_match_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('research_interests', models.ManyToManyField(blank=True, related_name='researcher_profiles', to='profiles.researchinterest')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PreferredInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_by_researchers', to='universities.university')),
                ('researcher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_institutions', to='profiles.researcherprofile')),
            ],
            options={
                'ordering': ['priority', 'university__name'],
                'constraints': [models.UniqueConstraint(fields=('researcher_profile', 'university'), name='unique_profile_preferred_institution')],
            },
        ),
    ]
