# Generated by Django 5.2.17 on 2026-09-26 13:17

from django.db import migrations, models


ROLES = {
    'Academic': {
        'Professor': ['Profesor', 'Faculty Member'],
        'Associate Professor': ['Profesor Asociado'],
        'Assistant Professor': ['Profesor Asistente'],
        'Lecturer': ['Docente'],
        'Senior Lecturer': ['Docente Senior'],
        'Adjunct': ['Adjunct Professor', 'Profesor Adjunto'],
        'Visiting Professor': ['Profesor Visitante'],
    },
    'Education': {
        'English Teacher': ['English Instructor', 'Profesor de Ingles'],
        'TESOL Instructor': ['ESL Instructor', 'EFL Instructor'],
        'Curriculum Developer': ['Curriculum Specialist'],
        'Instructional Designer': ['Learning Designer'],
    },
    'Research': {
        'Researcher': ['Research Fellow', 'Investigador'],
        'Research Scientist': ['Cientifico Investigador'],
        'Research Assistant': ['Asistente de Investigacion'],
        'Postdoctoral Researcher': ['Postdoc', 'Postdoctoral Fellow'],
        'Research Consultant': ['Consultor de Investigacion'],
    },
    'Consulting': {
        'Educational Consultant': ['Education Consultant'],
        'AI Consultant': ['Artificial Intelligence Consultant'],
        'NLP Consultant': ['Natural Language Processing Consultant'],
        'Technology Consultant': ['Tech Consultant'],
    },
    'Industry': {
        'AI Engineer': ['Artificial Intelligence Engineer'],
        'Machine Learning Engineer': ['ML Engineer'],
        'NLP Engineer': ['Natural Language Processing Engineer'],
        'Data Scientist': ['Cientifico de Datos'],
        'Python Developer': ['Python Engineer'],
        'Software Engineer': ['Software Developer'],
    },
    'Management': {
        'Academic Coordinator': ['Coordinador Academico'],
        'Program Director': ['Director de Programa'],
        'Department Chair': ['Department Head', 'Jefe de Departamento'],
    },
}


def seed_job_roles(apps, schema_editor):
    JobRole = apps.get_model('profiles', 'JobRole')
    for category, roles in ROLES.items():
        for name, aliases in roles.items():
            JobRole.objects.update_or_create(
                name=name,
                defaults={
                    'category': category,
                    'aliases': aliases,
                    'is_active': True,
                },
            )


def remove_seeded_job_roles(apps, schema_editor):
    JobRole = apps.get_model('profiles', 'JobRole')
    names = [name for roles in ROLES.values() for name in roles]
    JobRole.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Education', 'Education'), ('Research', 'Research'), ('Consulting', 'Consulting'), ('Industry', 'Industry'), ('Management', 'Management')], max_length=20)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='preferred_roles',
            field=models.ManyToManyField(blank=True, related_name='researcher_profiles', to='profiles.jobrole'),
        ),
        migrations.RunPython(seed_job_roles, remove_seeded_job_roles),
    ]
