# Generated by Django 5.2.17 on 2026-09-26 13:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0002_jobrole_researcherprofile_preferred_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('matched', models.BooleanField(default=False)),
                ('explanation', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.job')),
                ('matched_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_matches', to='profiles.jobrole')),
                ('researcher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='profiles.researcherprofile')),
            ],
            options={
                'ordering': ['-score', '-computed_at'],
                'indexes': [models.Index(fields=['researcher_profile', 'score'], name='match_profile_score_idx'), models.Index(fields=['matched'], name='match_matched_idx'), models.Index(fields=['computed_at'], name='match_computed_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'researcher_profile'), name='unique_job_researcher_match')],
            },
        ),
    ]
