# Generated by Django 5.2.17 on 2026-09-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_profiles(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    ResearcherProfile = apps.get_model('profiles', 'ResearcherProfile')
    for profile in ResearcherProfile.objects.filter(user__isnull=True):
        user = User.objects.create(
            username=f"vs018-profile-{profile.pk}",
            password="!",
        )
        profile.user = user
        profile.save(update_fields=['user'])


def preserve_assigned_users(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_jobmatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researcher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(assign_existing_profiles, preserve_assigned_users),
        migrations.AlterField(
            model_name='researcherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researcher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
